### ISSUE TITLE
badge assertion appears to be invalid

### ISSUE THREAD

**Issue by strongcord** [davelester/WPBadger#40] opened 2012-11-12 05:39 UTC
"We have encountered the following problem: badge assertion appears to be invalid"

Spent a couple of days researching before adding this issue...

Using both your plugins...  WPbadger.0.6.2 & WPbadgeDisplay.0.8

Using dedicated server, so can have administrator do whatever is necessary.

Do not know where to find the .json file to validate it

Researched .json file structure and built a hand-made badge and the badge assertion file passed the openbadges validator: http://beta.openbadges.org/issuer/validator

That's when I found that the .json email addresses cannot handle uppercase in domain name.

Other than that the format of the information required in the WPbadger Config seems to match  what I saw demonstrated in the hand-made badge .json file.

However... when trying to use the baker....
http://beta.openbadges.org/baker?assertion=http://mini4wd.com/badge-assertion03.json

get this error...
"{"message":"Unexpected content-type: Response is `text/plain`, but expected `application/json`","name":"ContentTypeError"}"

...i saved the .json file as .json and not as .txt and FTP using binary not ascii.

Maybe the baker give a clue to what I am doing wrong with your plugins.

Am I clueless?

Thank you and peace all around

**Comment by davelester** [comment] 2012-11-16 03:22
Could you share the url of your award json so I could take a closer look?

**Comment by davelester** [comment] 2013-02-01 00:27
I'm closing this ticket because the problem was likely caused by invalid data being entered into the post type. Feel free to share the link to your award so I can continue debugging -- the upcoming release of WPBadger will add some validation to hopefully prevent or reduce the number of similar problems that folks run into.

**Closed as completed by davelester** 2013-02-01 00:27 UTC
